/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DoRouteImport } from './routes/do'
import { Route as BeRouteImport } from './routes/be'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DoUeberMichRouteImport } from './routes/do.ueber-mich'
import { Route as DoSkillsRouteImport } from './routes/do.skills'
import { Route as DoReferenzenRouteImport } from './routes/do.referenzen'
import { Route as DoKontaktRouteImport } from './routes/do.kontakt'
import { Route as DoImpressumRouteImport } from './routes/do.impressum'

const DoRoute = DoRouteImport.update({
  id: '/do',
  path: '/do',
  getParentRoute: () => rootRouteImport,
} as any)
const BeRoute = BeRouteImport.update({
  id: '/be',
  path: '/be',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoUeberMichRoute = DoUeberMichRouteImport.update({
  id: '/ueber-mich',
  path: '/ueber-mich',
  getParentRoute: () => DoRoute,
} as any)
const DoSkillsRoute = DoSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => DoRoute,
} as any)
const DoReferenzenRoute = DoReferenzenRouteImport.update({
  id: '/referenzen',
  path: '/referenzen',
  getParentRoute: () => DoRoute,
} as any)
const DoKontaktRoute = DoKontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => DoRoute,
} as any)
const DoImpressumRoute = DoImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => DoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/be': typeof BeRoute
  '/do': typeof DoRouteWithChildren
  '/do/impressum': typeof DoImpressumRoute
  '/do/kontakt': typeof DoKontaktRoute
  '/do/referenzen': typeof DoReferenzenRoute
  '/do/skills': typeof DoSkillsRoute
  '/do/ueber-mich': typeof DoUeberMichRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/be': typeof BeRoute
  '/do': typeof DoRouteWithChildren
  '/do/impressum': typeof DoImpressumRoute
  '/do/kontakt': typeof DoKontaktRoute
  '/do/referenzen': typeof DoReferenzenRoute
  '/do/skills': typeof DoSkillsRoute
  '/do/ueber-mich': typeof DoUeberMichRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/be': typeof BeRoute
  '/do': typeof DoRouteWithChildren
  '/do/impressum': typeof DoImpressumRoute
  '/do/kontakt': typeof DoKontaktRoute
  '/do/referenzen': typeof DoReferenzenRoute
  '/do/skills': typeof DoSkillsRoute
  '/do/ueber-mich': typeof DoUeberMichRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/be'
    | '/do'
    | '/do/impressum'
    | '/do/kontakt'
    | '/do/referenzen'
    | '/do/skills'
    | '/do/ueber-mich'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/be'
    | '/do'
    | '/do/impressum'
    | '/do/kontakt'
    | '/do/referenzen'
    | '/do/skills'
    | '/do/ueber-mich'
  id:
    | '__root__'
    | '/'
    | '/be'
    | '/do'
    | '/do/impressum'
    | '/do/kontakt'
    | '/do/referenzen'
    | '/do/skills'
    | '/do/ueber-mich'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BeRoute: typeof BeRoute
  DoRoute: typeof DoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/do': {
      id: '/do'
      path: '/do'
      fullPath: '/do'
      preLoaderRoute: typeof DoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/be': {
      id: '/be'
      path: '/be'
      fullPath: '/be'
      preLoaderRoute: typeof BeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/do/ueber-mich': {
      id: '/do/ueber-mich'
      path: '/ueber-mich'
      fullPath: '/do/ueber-mich'
      preLoaderRoute: typeof DoUeberMichRouteImport
      parentRoute: typeof DoRoute
    }
    '/do/skills': {
      id: '/do/skills'
      path: '/skills'
      fullPath: '/do/skills'
      preLoaderRoute: typeof DoSkillsRouteImport
      parentRoute: typeof DoRoute
    }
    '/do/referenzen': {
      id: '/do/referenzen'
      path: '/referenzen'
      fullPath: '/do/referenzen'
      preLoaderRoute: typeof DoReferenzenRouteImport
      parentRoute: typeof DoRoute
    }
    '/do/kontakt': {
      id: '/do/kontakt'
      path: '/kontakt'
      fullPath: '/do/kontakt'
      preLoaderRoute: typeof DoKontaktRouteImport
      parentRoute: typeof DoRoute
    }
    '/do/impressum': {
      id: '/do/impressum'
      path: '/impressum'
      fullPath: '/do/impressum'
      preLoaderRoute: typeof DoImpressumRouteImport
      parentRoute: typeof DoRoute
    }
  }
}

interface DoRouteChildren {
  DoImpressumRoute: typeof DoImpressumRoute
  DoKontaktRoute: typeof DoKontaktRoute
  DoReferenzenRoute: typeof DoReferenzenRoute
  DoSkillsRoute: typeof DoSkillsRoute
  DoUeberMichRoute: typeof DoUeberMichRoute
}

const DoRouteChildren: DoRouteChildren = {
  DoImpressumRoute: DoImpressumRoute,
  DoKontaktRoute: DoKontaktRoute,
  DoReferenzenRoute: DoReferenzenRoute,
  DoSkillsRoute: DoSkillsRoute,
  DoUeberMichRoute: DoUeberMichRoute,
}

const DoRouteWithChildren = DoRoute._addFileChildren(DoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BeRoute: BeRoute,
  DoRoute: DoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
